name: Publish package to the Maven Central Repository
on:
  release:
    types: [created,edited]

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Maven Central Repository
        uses: actions/setup-java@v3
        with:
          java-version: '17.0.8+7'
          distribution: 'temurin'
          server-id: ossrh
          server-username: MAVEN_USERNAME
          server-password: MAVEN_PASSWORD
          overwrite-settings: true
        env:
          MAVEN_USERNAME: ${{ secrets.OSSRH_USERNAME }}
          MAVEN_PASSWORD: ${{ secrets.OSSRH_TOKEN }}
      - uses: s4u/maven-settings-action@v2.8.0
        with:
          servers: |
            [{
                "id": "ossrh",
                "username": "${{ secrets.OSSRH_USERNAME }}",
                "password": "${{ secrets.OSSRH_TOKEN }}"
            }]
      - name: Publish package
        run: mvn -Drevision=${{ github.event.release.tag_name }} --batch-mode deploy